### PR TITLE
instead of including flag icons, add flags gem dependency

### PR DESCRIPTION
**Pull request by mrbrdo**

### CODE REVIEW

**Comment by wjwitek** [comment]
Hey, @mrbrdo I was testing this PR and unforutnately when I configure spree to allow selection of store (where the flags are used), those chagnes seem to break something and dropdown menu looks like normal:
Screenshot 2022-12-05 at 16 21 37
while it should be displaying available stores like this:
Screenshot 2022-12-05 at 16 18 10

Have you tested those changes or maybe also changed something that is not commited here?

**Comment by mrbrdo** [comment]
@wjwitek hm I don't remember it showing like that in the dropdown, was it always like that since 4.3 (it's when I started using Spree)?
My dropdown indeed looks like your first screenshot, but I think it had always looked like that. I have the current flag displayed as the icon instead of the globe (next to cart icon), which I probably changed myself, and the flag works there.

**Comment by mrbrdo** [comment]
I tried reverting my commit and even using the spree main branch of the frontend, but I still do not see the icons as in your second screenshot. I don't remember it ever showing up like that for me. Perhaps that functionality is broken in different ways as well?

**Comment by mrbrdo** [comment]
@wjwitek so just to be sure I cloned the latest spree_starter, added spree_frontend (4.5), and still, I do not see the icons in the globe dropdown. I just went into admin and added a few languages to the default store. But I am not sure if you are talking about a multi-store configuration or something like that?

**Comment by wjwitek** [comment]
@mrbrdo Yes, I'm talking about multi-store configuration, becouse that was the only place that I found to use flags. It's possible that to make flags gem work for it some changes to function retrieving flag for it would have to be made.

**Comment by mrbrdo** [comment]
@wjwitek can you give a little instruction on this configuration? I tried to create a few stores, but I don't get any switch menu after I create the second store. There is no world icon next to the cart icon anymore.
I'm trying to see the issue you are describing.

**Comment by wjwitek** [comment]
@mrbrdo Yes, of course. As far as I know it's not something you can change via admin panel, but in general it's part of frontend's configuration, a preference called :show_store_selector which has to be set to true, for example using rails console: `Spree::Config.show_store_selector = true`

**Comment by mrbrdo** [comment]
@wjwitek the correct option is now `Spree::Frontend::Config.show_store_selector`.
I tried it, but it works fine even with my changes to flags:

`gem 'spree_frontend', github: 'mrbrdo/spree_legacy_frontend', branch: 'flags_gem'`

Here is my `spree_starter` I used to test this (`flags_gem` branch):
https://github.com/mrbrdo/spree_starter/tree/flags_gem

Are you sure you didn't make some changes which could be affecting this? Do you have the same issue with a fresh spree_starter?

**Comment by wjwitek** [comment]
@mrbrdo I've tried it again and it works alright. I have no idea what I have done wrong before, sorry for the trouble.

**Comment by mrbrdo** [comment]
@wjwitek no problem, glad that we sorted it out :)

**Comment by mrbrdo** [comment]
@nciemniak since it seems the above issue was not related, would you like to merge this?

**Comment by nciemniak** [comment]
@mrbrdo yep, definitely! thanks for confirming that everything works :tada:

**Pull request merged**
